---
- name: Container Open-WebUI & port 443
  hosts: all
  become: yes  
  tasks:
    - name: Open-WebUI running
      ansible.builtin.command:
        cmd: docker ps --filter "name=open-webui" --format "{{.Names}}"
      register: running_containers
      changed_when: false

    - name: Delete container
      ansible.builtin.command:
        cmd: docker rm -f open-webui
      when: "'open-webui' in running_containers.stdout_lines"
      ignore_errors: true

    - name: run container Open-WebUI
      ansible.builtin.command:
        cmd: >-
          docker run -d -p 443:8080
          -v open-webui:/app/backend/data
          --name open-webui --restart always
          quay.io/mgiessing/open-webui:v0.5.7

    - name: Waiting
      ansible.builtin.wait_for:
        port: 443
        delay: 5  
        timeout: 30  
        state: started
      register: service_check

    - name: check port 443
      ansible.builtin.debug:
        msg: >-
          open port 443
        when: service_check.state == "started"

    - name: website not running
      ansible.builtin.fail:
        msg: "website not running."
      when: service_check.state != "started"
